FROM node:17-alpine

WORKDIR /app

RUN apk add nano \
    procps \
    bash

# update and install dependency
RUN apk update && apk upgrade

COPY ./deploy/local/bash/nuxt-init.sh /usr/local/bin/nuxt-init
RUN chmod 0777 /usr/local/bin/nuxt-init

# copy the app, note .dockerignore
RUN npm install
RUN npm i -g nuxt
RUN npm run build

ENTRYPOINT ["npm", "run", "dev"]